### ISSUE TITLE
Issue running `select *` with jdbc connector

### ISSUE THREAD

**Issue by omrigivoni** [wix/quix#171]
I'm utilizing the generic JDBC connector in order to connect to PostgreSQL database (using org.postgresql as a dependency).
Everything works perfectly except for `select * ...` queries, which cause an error:
```
backend_1          | 2019-09-26 21:40:51,519 ERROR [presto-io-39]                 quix.core.utils.TaskOps$ : event=execution-failure socket-id=9c0cefd7-c09f-187c-9942-0ebbad02d93a sql=[select *-newline-from table;-newline-]
backend_1          | java.lang.NullPointerException
backend_1          | 	at quix.jdbc.JdbcQueryExecutor.$anonfun$prepareBatch$3(JdbcQueryExecutor.scala:37)
backend_1          | 	at quix.jdbc.JdbcQueryExecutor.$anonfun$prepareBatch$3$adapted(JdbcQueryExecutor.scala:33)
backend_1          | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
backend_1          | 	at scala.collection.immutable.Range.foreach(Range.scala:155)
backend_1          | 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
backend_1          | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
backend_1          | 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
backend_1          | 	at quix.jdbc.JdbcQueryExecutor.$anonfun$prepareBatch$1(JdbcQueryExecutor.scala:33)
backend_1          | 	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
backend_1          | 	at monix.eval.Task$.unsafeStartNow(Task.scala:4249)
backend_1          | 	at monix.eval.internal.TaskBracket$BaseStart$$anon$1.onSuccess(TaskBracket.scala:143)
backend_1          | 	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
backend_1          | 	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108)
backend_1          | 	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:128)
backend_1          | 	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
backend_1          | 	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
backend_1          | 	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
backend_1          | 	at monix.execution.internal.Trampoline.execute(Trampoline.scala:39)
backend_1          | 	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
backend_1          | 	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
backend_1          | 	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
backend_1          | 	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:34)
backend_1          | 	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:72)
backend_1          | 	at monix.eval.internal.TaskRace$Register$$anon$1.onSuccess(TaskRace.scala:57)
backend_1          | 	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
backend_1          | 	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:192)
backend_1          | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
backend_1          | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
backend_1          | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by omrigivoni** [comment]
Resolved after pulling the latest code

**Comment by frolovv** [comment]
hey @omrigivoni, i'm back from long vacation, will look into this soon!

**Comment by omrigivoni** [comment]
Thanks @frolovv!
Worth to mention that it doesn’t happen always, just on certain field type with certain value. I didn’t get to the bottom of it, but happy to send you some more debug information if you need, just let me know.
